### ISSUE TITLE
Is it possible to move the cursor away while generating?

### ISSUE THREAD

**Issue by LintaoAmons** [Robitx/gp.nvim#20]
I have a split buffer and asking ChatGPT the questions, and at the meanwhile I want do some viewing or editing work at another buffer.

Currently it will lead to an error if I move my cursor away from the gpt-writing buffer

**Comment by Robitx** [comment]
@LintaoAmons Hey, try the latest version please. It's not perfect - when you move to other window, it breaks `undojoin` (which joins together all write/delete operations so, the full response can be undone with single `u`) into two parts (so you'd have to hit `u` twice to erase response), but otherwise it seems to work.

**Comment by LintaoAmons** [comment]
![Uploading show.gif…]()

Super cool!
