### ISSUE TITLE
Shouldn't GpImplement append?

### ISSUE THREAD

**Issue by potamides** [Robitx/gp.nvim#22]
Thanks for this cool plugin! I know that `GpImplement` is just an example hook function but the comments say the following:

>GpImplement finishes the provided selection/range based on comments in the code

But *finishing* would mean appending to the already existing code, currently it uses `gp.Target.rewrite`. Is that intended?

**Comment by Robitx** [comment]
@potamides Hey, sorry for late response.

Yes the original GpImplement was intended as a rewrite, for example taking:
``` python
# imports here

# fib(n) using simple recursion

# main function here reading n as first argument
```
and calling `:%GpImplement` will get you something like:
``` python
import sys


def fib(n):
    if n <= 1:
        return n
    else:
        return fib(n - 1) + fib(n - 2)


if __name__ == "__main__":
    n = int(sys.argv[1])

    result = fib(n)
    print(result)
```

I've change the wording in the last version to reflect that.

But there is nothing stopping you from overriding the Implement function in your config or making another one using append instead. :slightly_smiling_face: Looking for the usage in the wild, [this guy seems to have some nice examples of custom hooks](https://github.com/frankroeder/dotfiles/blob/ca4be698194e54f02498f85c26324346f2ed37c7/nvim/lua/plugins/gp_nvim.lua#L19) including the GpComplete using append.


_I was thinking lately, that in the next phase I should focus on building "repository of useful hooks" so that people don't have to individually reinvent the wheel + doing some prompt engineering on the commands to increase the chance of gpt providing right answers._

**Comment by potamides** [comment]
I see, thank you for the detailed response. That repository indeed contains some nice examples and the repository of useful hooks is something I am looking forward to as well :)
