### ISSUE TITLE
Inconsistent behavior for GpRewrite spacing

### ISSUE THREAD

**Issue by lpleahy** [Robitx/gp.nvim#28]
Most of the time when I run `GpRewrite` on a selection of text in visual mode, it doesn't indent the code in the right place. It occasionally gets this right though, as far as I can tell it only ever works on a single line, but I could be wrong.

**Comment by Robitx** [comment]
@lpleahy Hey, are you using gpt3.5 or gpt4? I don't notice this as much, since I generally just hit format + occasionally re indent the selected block using shortcuts. If you get me some examples where it consistently fails for you, I'll try to fine tune the default instructions for the commands to increase the chance it will respect original indenting.

**Comment by Robitx** [comment]
@lpleahy Sorry it took so long, forcing the gpt models by instructions to respect spacing was a dead end. So instead the plugin handles it by striping minimal white space prefix for selected lines and putting the the prefix back for the answer received from gpt.

Please give it a go if you're still interested.
