### ISSUE TITLE
Support for restricted context of chats

### ISSUE THREAD

**Issue by festeh** [Robitx/gp.nvim#30]
Hi!

I've noticed in my chats that often only a single last message is enough for a prompt (+ chat header), sometimes only last two messages with response to a previous one would suffice. For now the solution would be to just create a new chat, but that means I'll need to copy a chat header. This can be solved with chat templates, but another solution is to add a command like `GpChatRespondLast N` that would restrict a prompt to last N messages and N - 1 responses. Do you think that would be a good feature? If so, I can work on a PR.

**Comment by Robitx** [comment]
@festeh Hey, yeah this would be useful. But instead of adding new command, I think it would be better to make `:GpChatRespond` accept [ranges](https://vim.fandom.com/wiki/Ranges) in a similar way as text operation commands such as GpRewrite. This way it would be much more flexible and building `GpChatRespondLast N` on top of this would be trivial.

If you have time for PR go for it, otherwise I'll get around to it in a week or two.

**Comment by Robitx** [comment]
@festeh Thanks for the PR. I've tweaked it a little bit so that `:GpChatRespond N` works as  `:GpChatLimitedRespond N`.

The only thing lost by not introducing another command is the default `:GpChatLimitedRespond` which requires writing `:GpChatRespond 1`. At this moment I honestly don't know what N will be most popular and if N=1 is special enough to deserve a separate command. But we can easily remedy this in the future.

Thanks again and enjoy your vacation.
