### ISSUE TITLE
Finally! I've been waiting for this plugin 💛

### ISSUE THREAD

**Issue by alextes** [Robitx/gp.nvim#34]
I've tried a lot of AI plugins, here's a [reddit post](https://www.reddit.com/r/neovim/comments/12aek0y/ai_plugin_overview/) where I look at a dozen of them. All but Copilot I ended up removing after a while. This plugin I've had for a week and I'm only getting more excited about its integration in my workflow.

Thank you, please keep up the good work! 🙏

**Comment by divramod** [comment]
same for me, it saved me a aweful lot of time.

thx!

**Comment by divramod** [comment]
@alextes is there a reason you archived the reddit post? i hope you haven't switched to cursor 🤣 i watched the cursor intro video you linked in the post and really liked it. we need to help make gp.nvim better to come as close as possible to cursor, or even surpass it ;-) maybe you can at least link gp.nvim in the post, so that some more traffic will be generated here, which maybe could help improve the plugin. i tried about 50-70% of the plugins you mentioned and ended up with gp.nvim :-)

**Comment by alextes** [comment]
@divramod archiving is automatic 😒 . In retrospect reddit is not a good place to make an overview like that exactly because a post is forced to decay. Still, I was allowed to edit the post still so done! Highly positive entry added.
