### ISSUE TITLE
Allow generation stop

### ISSUE THREAD

**Issue by teocns** [Robitx/gp.nvim#63]
With issue #52 we have fixed concurrent, parallel generations on `<C-g>`. 

This command could be potentially enabled to stop generation while running;

**Comment by Robitx** [comment]
Hey, there already is a plugin wide `:GpStop` command with [recommended shortcut](https://github.com/Robitx/gp.nvim#shortcuts) `<C-g>s` but people can choose a different one. :slightly_smiling_face:

I'd prefer not to put it on the same shortcut exactly because of #52 - people might hit `<C-g>` more times than they wanted by accident.

What might be beneficial is to set `<C-g>s`automatically for chat buffers and mention it in the chat template so that people don't have to memorize it.

@teocns What do you think?

**Comment by teocns** [comment]
Yes indeed, let's add it so it's more intuitive; its absence is the main reason I opened this issue. Thank you!
